source ~/.zsh/exports.zsh
source ~/.zsh/checks.zsh
source ~/.zsh/colors.zsh
source ~/.zsh/setopt.zsh
source ~/.zsh/keybinds.zsh

# ZSH
ZSH_THEME="muse"
CASE_SENSITIVE="true"
DISABLE_AUTO_UPDATE="true"
ENABLE_CORRECTION="true"

# Plug-ins
plugins=(git)

source $ZSH/oh-my-zsh.sh

source ~/.zsh/aliases.zsh